# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Article.create(title: 'AI')
Article.create(title: 'Blockchain')
Article.create(title: 'C++')
Article.create(title: 'Docker')
Article.create(title: 'ElasticSearch')
Article.create(title: 'Fluentd')
Article.create(title: 'Golang')
Article.create(title: 'Hadoop')
Article.create(title: 'InfluxDB')
Article.create(title: 'Java')
Article.create(title: 'Kafka')
Article.create(title: 'Logstash')
Article.create(title: 'MongoDB')
Article.create(title: 'Nginx')
Article.create(title: 'OOP')
Article.create(title: 'Python')
Article.create(title: 'Q')
Article.create(title: 'Ruby')
Article.create(title: 'SRE')
Article.create(title: 'TSDB')
Article.create(title: 'Unicode')
Article.create(title: 'Vagrant')
Article.create(title: 'Wordpress')
Article.create(title: 'X')
Article.create(title: 'Yaml')
Article.create(title: 'Zookeeper')
